-- ============================================================================
-- SCRIPT DE CRIAÇÃO DA TABELA DE PRODUTOS NO SUPABASE (FLOWER'S STORE)
-- ============================================================================
-- Como usar:
-- 1. Acesse o painel do Supabase (https://supabase.com/dashboard)
-- 2. No menu lateral esquerdo, clique em "SQL Editor"
-- 3. Cole todo este código e clique no botão verde "Run"
-- ============================================================================

-- 1. Cria a tabela de produtos
CREATE TABLE IF NOT EXISTS public.produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referencia TEXT NOT NULL,
    nome TEXT NOT NULL,
    categoria TEXT NOT NULL DEFAULT 'geral',
    descricao TEXT,
    preco NUMERIC(10,2) NOT NULL,
    preco_original NUMERIC(10,2),
    tag_desconto TEXT,
    imagem_url TEXT NOT NULL DEFAULT 'imagens/logo-flowers-store.jpg',
    imagem_alt TEXT,
    destaque_home BOOLEAN NOT NULL DEFAULT false,
    ativo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilita a Segurança por Linhas (Row Level Security - RLS)
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;

-- 3. Cria a política de leitura pública (permite que qualquer visitante do site veja os produtos ativos)
CREATE POLICY "Permitir leitura publica de produtos ativos"
ON public.produtos
FOR SELECT
TO public
USING (ativo = true);

-- 4. Insere os produtos iniciais do catálogo
INSERT INTO public.produtos (referencia, nome, categoria, descricao, preco, preco_original, tag_desconto, imagem_url, imagem_alt, destaque_home, ativo)
VALUES
    ('REF-001', 'Vestido Elegance Floral', 'vestidos', 'Vestido de seda floral com caimento leve, elegante e estampa floral exclusiva', 189.90, 270.00, '-30%', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&auto=format&fit=crop&q=80', 'Vestido de Seda Floral', true, true),
    ('REF-002', 'Jaqueta Jeans Premium', 'casacos', 'Jaqueta jeans com lavagem especial e caimento confortável', 219.90, 275.00, '-20%', 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&auto=format&fit=crop&q=80', 'Jaqueta Jeans Premium', true, true),
    ('REF-003', 'Sobretudo Clássico', 'casacos', 'Sobretudo clássico de lã ideal para dias frios e ocasiões elegantes', 299.90, 499.00, '-40%', 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=500&auto=format&fit=crop&q=80', 'Sobretudo de Lã', true, true),
    ('REF-004', 'Vestido Longo Azul Floral', 'vestidos', 'Vestido longo azul floral com detalhe especial na cintura', 149.99, 149.99, null, 'imagens/vestido-longo-azul.png', 'Vestido Longo Azul Floral', false, true),
    ('REF-005', 'Vestido Longo Colorido', 'vestidos', 'Vestido longo estampado alegre em cores vivas', 139.90, 139.90, null, 'imagens/vestido-longo-colorido.png', 'Vestido Longo Colorido', false, true),
    ('REF-006', 'Vestido Longo Verde', 'vestidos', 'Vestido longo verde com caimento fluido', 129.90, 129.90, null, 'imagens/vestido-longo-verde.png', 'Vestido Longo Verde', false, true),
    ('REF-007', 'Macacão Rosa Elegance', 'vestidos', 'Macacão longo em tom rosa delicado e sofisticado', 159.90, 159.90, null, 'imagens/macacao-rosa.png', 'Macacão Rosa Elegance', false, true),
    ('REF-008', 'Bermuda Clara', 'bermudas', 'Bermuda clara confortável e estilosa', 89.90, 89.90, null, 'imagens/bermuda-clara.png', 'Bermuda Clara', false, true),
    ('REF-009', 'Bermuda Escura', 'bermudas', 'Bermuda escura com corte reto e bolsos frontais', 79.90, 79.90, null, 'imagens/bermuda-escura.png', 'Bermuda Escura', false, true),
    ('REF-010', 'Bermuda Marrom', 'bermudas', 'Bermuda em tom marrom outonal, estilosa e versátil', 99.90, 99.90, null, 'imagens/bermuda-marrom.png', 'Bermuda Marrom', false, true),
    ('REF-011', 'Macacão Amarelo Manteiga', 'bermudas', 'Peça em tom suave amarelo manteiga em tecido leve', 89.90, 89.90, null, 'imagens/macacao-amarelo-manteiga.png', 'Macacão Amarelo Manteiga', false, true),
    ('REF-012', 'Camiseta Bege Listrada', 'camisetas', 'Camiseta básica em tom bege com listras clássicas', 49.90, 49.90, null, 'imagens/camiseta-bege-listrada.png', 'Camiseta Bege Listrada', false, true),
    ('REF-013', 'Camisa Bege Listras Manga Longa', 'camisetas', 'Camisa leve listrada com visual clean e contemporâneo', 59.90, 59.90, null, 'imagens/camisa-bege-listras.png', 'Camisa Bege Listras', false, true)
ON CONFLICT (id) DO NOTHING;
